### ISSUE TITLE
I was confused by one line in simulator.py

### ISSUE THREAD

**Issue by wjy-yy** [stanford-futuredata/InQuest#1]
In line [358](https://github.com/stanford-futuredata/InQuest/blob/042619ce164d739d75522ef414a8d715e07b3ddf/simulator.py#L358C5-L358C119), there is

```python
results['median_rmse'] = results_df.compute_median_segment_error(lambda row: compute_median_segment_error, axis=1)
```

but I could not understand the use of `DataFrame.compute_median_segment_error` and the lambda function.

Could you please tell me how to figure out this? Thanks so much.

**Comment by wjy-yy** [comment]
I guess the expression might be:

```python
results_df['median_rmse'] = [compute_median_segment_error(row) for row in results]
```

Is it right?

**Comment by team-aspen-protocol** [comment]
Hi there!

If my recollection is correct, this dataframe has one row per-trial, and for each trial we store the RMSE for each of the N segments (N=5) in its own column. We want to compute the median of these N=5 RMSE's for the trial. Thus, we execute this lambda with axis=1, so it's input is an entire row of the dataframe (I.e. one trial) and its output is the median of the per-segment RMSEs for that trial. Please let me know if this isn't clear, as I'd be happy to provide more pointers into the code once I'm at my laptop!

**Comment by mdr223** [comment]
Hi there!

If my recollection is correct, this dataframe has one row per-trial, and for each trial we store the RMSE for each of the N segments (N=5) in its own column. We want to compute the median of these N=5 RMSE's for the trial. Thus, we execute this lambda with axis=1, so it's input is an entire row of the dataframe (I.e. one trial) and its output is the median of the per-segment RMSEs for that trial. Please let me know if this isn't clear, as I'd be happy to provide more pointers into the code once I'm at my laptop!

**Comment by wjy-yy** [comment]
Thanks for your prompt reply. I think it is clear for me. I will recheck it. If the expression could be rewritten, would you mind my PR for that part?

I will continue to understand your great code. Looking for further discussion with you.

**Comment by mdr223** [comment]
My apologies for the delayed response! I'd be happy to consider a PR / revision as long as it logically computes the same outcome.

I might also suggest / encourage creating a fork of this repository if you'd like to do some more custom work of your own, as this repository is mostly meant to remain in a static state for future readers of our paper to be able to reproduce our results.
