### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by UelisonSantos** [stanford-futuredata/InQuest#2]
Hello, 

Thank you for sharing the repository. I am interested in running the queries and I am stuck in this error when running the command:

SyntaxError: invalid syntax
--- customer-support static ---
  File "<fstring>", line 1
    (os.path.join(results_dir, f'results-{config['sampling']['strategy']}-{predicate}-{dataset_name}{special}-alpha-{alpha}-segments-{num_segments}{pilot_str}.pq'))
                                                  ^
![image](https://github.com/stanford-futuredata/InQuest/assets/30526663/de584a31-dd8c-401f-b69b-ce20fdaf189a)

This same error keeps going for all datasets

Any clue what could it be?

Thank you!

**Comment by mdr223** [comment]
Hi there, apologies for the delayed response. I'm not sure how that bad f-string snuck into the simulator script, but I just pushed a commit to `main` which I think should fix that issue: https://github.com/stanford-futuredata/InQuest/commit/051c69842c0066c04442e8942911f5124b3083a2

Best,
Matthew
